---
title: CITES
output:
  html_document:
    number_sections: yes
    toc: no
    theme: bootstrap
    highlight: tango
    df_print: kable
  pdf_document:
    toc: yes
    df_print: kable
    number_sections: no
params:
  mes: NULL
date: "2025-06-23"
---

```{r echo=F, message=F, warning=F, results='markup'}
library(tidyverse)
library(rio)
library(sf)
library(janitor)
```

### Número de exportaciones por año

```{r echo=F, message=F, warning=F, results='markup'}
cites |> 
  group_by(anio) |>
  summarise(eventos = n_distinct(cod_permiso)) |> 
  mutate(anio = case_when(is.na(anio) ~ "No declarado",
                          T ~ anio)) |> 
  adorn_totals()
```
```{r echo=F, message=F, warning=F, results='markup'}
cites |> 
  group_by(anio) |>
  summarise(eventos = n_distinct(cod_permiso)) |> 
  mutate(anio = case_when(is.na(anio) ~ "No declarado",
                          T ~ anio)) |> 
  ggplot(aes(x = anio, y = eventos, fill = anio)) + 
  geom_col()
```

### Número de exportaciones por año y tipo

```{r echo=F, message=F, warning=F, results='markup'}
cites |> 
  group_by(anio, tipo) |>
  summarise(eventos = n_distinct(cod_permiso)) |> 
  mutate(anio = case_when(is.na(anio) ~ "No declarado",
                          T ~ anio)) |> 
  pivot_wider(names_from = anio, values_from = eventos, values_fill = 0) |> 
  adorn_totals() |> 
  adorn_totals("col")
```
```{r echo=F, message=F, warning=F, results='markup'}
cites |> 
  group_by(anio, tipo) |>
  summarise(eventos = n_distinct(cod_permiso)) |> 
  mutate(anio = case_when(is.na(anio) ~ "No declarado",
                          T ~ anio)) |> 
  ggplot(aes(x = anio, y = eventos, fill = tipo)) + 
  geom_col()
```

### Número de exportaciones por año y proposito

```{r echo=F, message=F, warning=F, results='markup'}
cites |> 
  group_by(anio, proposito) |>
  summarise(eventos = n_distinct(cod_permiso)) |> 
  mutate(anio = case_when(is.na(anio) ~ "No declarado",
                          T ~ anio),
         proposito = case_when(is.na(proposito) ~ "No declarado",
                          T ~ proposito)) |> 
  pivot_wider(names_from = anio, values_from = eventos, values_fill = 0) |> 
  adorn_totals() |> 
  adorn_totals("col")
```
```{r echo=F, message=F, warning=F, results='markup'}
cites |> 
  group_by(anio, proposito) |>
  summarise(eventos = n_distinct(cod_permiso)) |> 
  mutate(anio = case_when(is.na(anio) ~ "No declarado",
                          T ~ anio),
         proposito = case_when(is.na(proposito) ~ "No declarado",
                          T ~ proposito)) |> 
  ggplot(aes(x = anio, y = eventos, fill = proposito)) + 
  geom_col()
```

### Permisos por país

```{r echo=F, message=F, warning=F, results='markup'}
apoyo01 |> 
  mutate(`País` = factor(`País`, levels = apoyo01$País[c(3, 11:4, 2, 1)],
                         labels = apoyo01$País[c(3, 11:4, 2, 1)])) |> 
  ggplot(aes(x="", y=permisos, fill = `País`)) + 
  geom_bar(stat='identity')+
  coord_polar("y", start = pi/2)+
  #geom_text(aes(label=permisos),
  #         position=position_stack(vjust=0.5),color="white",size=3.5, stroke = 0.2)+
  # geom_text(aes(label=permisos),
  #           position=position_stack(vjust=0.5),color="black",size=3)+
  geom_shadowtext(aes(label=permisos),
                  position=position_stack(vjust=0.5),size=3, stroke = 0.2,
                  col="black", bg.color="white") + 
  
  scale_color_manual(values = colores) +
  scale_fill_manual(values = colores) +
  theme(panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.background = element_rect(fill="white"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.title.x = element_blank(),
        legend.box = "vertical",
        legend.box.spacing = unit(0.5, "cm"),
        legend.direction = "vertical", 
        legend.position = "right",
        legend.text = element_text(size=7),
        legend.title = element_text(size=8, hjust = 0.5),
        panel.border = element_rect(colour = "black", fill = NA))
```
